"""object meet model

Revision ID: d711ec555f6d
Revises: 8581e3e0fcdb
Create Date: 2023-06-01 19:14:15.859578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd711ec555f6d'
down_revision = '8581e3e0fcdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
